---
name: "Published package verification"

on:
  release:
    types: [published]

jobs:
  released-install:
    name: "Verify that released package can be installed"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4.3.1"
        with:
          python-version: "3.9"

      - name: "Install yacfg from PiPy repository"
        run: "pip install yacfg"

      - name: "Run yacfg help"
        run: "yacfg --help"

      - name: "Run yacfg list templates"
        run: "yacfg --list-templates"

      - name: "Run yacfg list templates"
        run: "yacfg --list-profiles"

      - name: "Run yacfg_batch help"
        run: "yacfg_batch --help"
